using Microsoft.AspNetCore.Mvc;
using SwiftMoviesApi.Models;
using SwiftMoviesApi.Services.Interfaces;
using System.Collections.Generic;

namespace SwiftMoviesApi.Controllers;

[ApiController]
[Route("api/[controller]")]
public class MovieController : ControllerBase
{
    private readonly IMovieService _movieService;

    public MovieController(IMovieService movieService)
    {
        _movieService = movieService;
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        var movies = await _movieService.GetMoviesAsync();
        return Ok(movies);
    }

    [HttpPost]
    public async Task<IActionResult> InsertMovie([FromBody] Movie movie)
    {
        if (movie == null)
        {
            return BadRequest("Movie data is required");
        }

        // Ensure ID is not set for new movies - it will be auto-generated by the database
        movie.Id = 0;

        var addedMovie = await _movieService.AddMovieAsync(movie);
        return CreatedAtAction(nameof(Get), new { }, addedMovie);
    }

    [HttpPost("update")]
    public async Task<IActionResult> UpdateMovie([FromBody] Movie movie)
    {
        if (movie == null || movie.Id <= 0)
        {
            return BadRequest("A valid movie ID is required for update.");
        }

        var updatedMovie = await _movieService.UpdateMovieAsync(movie);
        if (updatedMovie == null)
        {
            return NotFound($"Movie with ID {movie.Id} was not found.");
        }

        return Ok(updatedMovie);
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteMovie(int id)
    {
        if (id <= 0)
        {
            return BadRequest("A valid movie ID is required.");
        }

        var deleted = await _movieService.DeleteMovieAsync(id);
        if (!deleted)
        {
            return NotFound($"Movie with ID {id} was not found.");
        }

        return NoContent();
    }
}
