namespace SwiftMoviesApi.Models;

public class Movie
{
    // Auto-generated by database on insert
    public int Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public int Year { get; set; }
}
